apps/cases/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.cases.views import get_home

urlpatterns = [
    path('home', login_required(get_home), name='home')
]

apps/countries/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from apps.countries.views import get_countries, search_countries, get_cases_by_country

urlpatterns = [
    path('countries', login_required(get_countries), name='countries'),
    path('search-countries', login_required(search_countries), name='search-countries'),
    path('cases-country/<str:country_code_alpha_three>', login_required(get_cases_by_country), name='cases-country'),
    path('api/', include(('apps.countries.api_urls', 'api'), namespace='api')),
]

apps/users/urls.py
from django.urls import include, path
from apps.users.views import create_user

urlpatterns = [
    path('create-user', create_user, name='create-user'),
]

dashboardcovid/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='web/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('cases/', include(('apps.cases.urls', 'cases'), namespace='cases')),
    path('countries/', include(('apps.countries.urls', 'countries'), namespace='countries')),
    path('users/', include(('apps.users.urls', 'countries'), namespace='users')),
]

apps/countries/models.py
from django.db import models

# Create your models here.

class Country(models.Model):
    name_spanish = models.CharField(max_length=100)
    name_english = models.CharField(max_length=100)
    slug_spanish = models.SlugField(max_length=100)
    slug_english = models.SlugField(max_length=100)
    code_alpha_two = models.CharField(max_length=5)
    code_alpha_three = models.CharField(max_length=5)

apps/users/models.py
from django.db import models

# Create your models here.

apps/users/forms.py
from django import forms
from django.contrib.auth.models import User

class CreateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
        ]

apps/cases/views.py
from django.shortcuts import render
from dashboardcovid.settings import headers_rapidapi
import requests
import datetime
import json

# Create your views here.

def get_home(request):
    url = 'https://covid-19-data.p.rapidapi.com/report/totals'
    response = requests.request('GET', url, headers=headers_rapidapi)
    cases = response.json()
    context = {
        'cases': cases,
    }
    return render (request, 'web/home.html' ,context)

apps/countries/views.py
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from apps.countries.models import Country
from django.template.defaultfilters import slugify
from dashboardcovid.settings import headers_rapidapi
import requests
import json
from deep_translator import GoogleTranslator
import datetime
import time

# Create your views here.

#Se utiliza una API para obtener el listado de países en inglés
def save_countries():
    Country.objects.all().delete()
    url = 'https://restcountries.eu/rest/v2/all'
    response = requests.request('GET', url)
    countries = response.json()
    available_countries = []
    for country in countries:
        country_name_en = country['name']
        #Se utiliza Google Translator para traducir el nombre del país
        #En caso de error en la traducción, el nombre del país queda igual que el original 
        try:
            country_name_es = GoogleTranslator(source='en', target='es').translate(country_name_en)            
        except Exception as e:
            country_name_es = country_name_en
        new_country = Country()
        new_country.name_spanish = country_name_es
        new_country.name_english = country_name_en
        new_country.slug_spanish = slugify(country_name_es)
        new_country.slug_english = slugify(country_name_en)
        new_country.code_alpha_two = country['alpha2Code']
        new_country.code_alpha_three = country['alpha3Code']
        available_countries.append(new_country)
    #Se crean los países de forma masiva
    Country.objects.bulk_create(available_countries)
    return True

#Se corrige el slug en español de los países
#Se utiliza bulk_update para actualizar los registros de forma masiva
def fix_slug():
    countries = Country.objects.all()
    fixed_countries = []
    for country in countries:
        new_country = Country()
        new_country.id = country.id
        new_country.slug_spanish = slugify(country.name_spanish)
        fixed_countries.append(new_country)
    Country.objects.bulk_update(fixed_countries, ['slug_spanish'])
    return True

def get_countries(request):
    countries = Country.objects.all()
    context = {
        'countries': countries
    }
    return render (request, 'web/countries.html', context)

def search_countries(request):
    country_search = request.GET.get('country_search', None)
    #La búsqueda se puede hacer por nombre o por código alfa
    #Se utiliza trigram search sobre los nombres en inglés y en español
    #Se reduce el valor del threshold para ampliar los valores de búsqueda
    countries = Country.objects.annotate(
        similarity_en = TrigramSimilarity('name_english', country_search)
    ).annotate(
        similarity_es = TrigramSimilarity('name_spanish', country_search)
    ).filter(
        Q(similarity_en__gte = 0.25) |
        Q(similarity_es__gte = 0.25) |
        Q(code_alpha_two = country_search.upper()) |
        Q(code_alpha_three = country_search.upper()) |
        Q(name_english__icontains = country_search) |
        Q(name_spanish__icontains = country_search)
    )
    context = {
        'countries': countries,
        'country_search': country_search
    }
    return render (request, 'web/countries.html', context)

def get_cases_by_country(request, country_code_alpha_three):
    country = get_object_or_404(Country, code_alpha_three = country_code_alpha_three)
    #Se obtienen los casos actuales por país
    url = 'https://covid-19-data.p.rapidapi.com/country/code'
    querystring = {
        'code': country.code_alpha_three,
    }
    response = requests.request('GET', url, headers=headers_rapidapi, params=querystring)
    cases = response.json()
    time.sleep(1)
    #Se obtienen los casos del 2020-06-18 por provincia
    #Se utiliza esa fecha porque es la última de la cual se obtienen datos
    url = 'https://covid-19-data.p.rapidapi.com/report/country/code'
    querystring = {
        'code': country.code_alpha_three,
        'date': '2020-06-18'
    }
    response = requests.request('GET', url, headers=headers_rapidapi, params=querystring)
    provinces = response.json()
    context = {
        'country': country,
        'cases': cases,
        'provinces': provinces
    }
    return render (request, 'web/cases_by_country.html', context)
    

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from apps.users.forms import CreateUserForm
from django.contrib.auth import password_validation

# Create your views here.

def create_user(request):
    context = {}
    if request.method == 'POST':
        form_user = CreateUserForm(request.POST)
        if form_user.is_valid():
            try:
                password = form_user.data['password']
                print(password)
                form_user = form_user.save(commit = False)
                password_validation.validate_password(password)
                form_user.set_password(password)
                form_user.save()
                return redirect ('login')
            except Exception as e:
                context['errors_1'] = e
        else:
            context['errors_2'] = form_user.errors
    return render(request, 'web/create_user.html', context)

templates/web/cases_by_country.html
{% extends 'web/master.html' %}

{% load staticfiles %}
{% load humanize %}

{% block content %}

<div class="container-fluid">
    <h1 class="mt-4">Casos Actuales - {{cases.0.lastUpdate}}</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">{{ country.name_spanish }} - {{ country.name_english }}</li>
    </ol>
    <div class="row">
        <div class="col-xl-3 col-md-6">
            <div class="card bg-primary text-white mb-4">
                <div class="card-body">Confirmados</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <label class="small text-white">{{ cases.0.confirmed|intcomma }}</label>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-warning text-white mb-4">
                <div class="card-body">Recuperados</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <label class="small text-white">{{ cases.0.recovered|intcomma }}</label>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-success text-white mb-4">
                <div class="card-body">Fallecidos</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <label class="small text-white">{{ cases.0.deaths|intcomma }}</label>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-danger text-white mb-4">
                <div class="card-body">Críticos</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <label class="small text-white">{{ cases.0.critical|intcomma }}</label>
                </div>
            </div>
        </div>
    </div>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Histórico de Casos por Provincias
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Provincia</th>
                            <th>Confirmados</th>
                            <th>Recuperados</th>
                            <th>Activos</th>
                            <th>Fallecidos</th>
                            <th>Fecha</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for province in provinces.0.provinces %}
                        <tr>
                            <td>{{province.province}}</td>
                            <td>{{province.confirmed|intcomma}}</td>
                            <td>{{province.recovered|intcomma}}</td>
                            <td>{{province.active|intcomma}}</td>
                            <td>{{province.deaths|intcomma}}</td>
                            <td>{{provinces.0.date}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}

<script>

var cases = {{cases|safe}}

</script>

<script src="{% static 'assets/demo/active-cases.js' %}"></script>

{% endblock %}

templates/web/countries.html
{% extends 'web/master.html' %}

{% load staticfiles %}
{% load humanize %}

{% block content %}

<div class="container-fluid">
    <h1 class="mt-4">Casos en el Mundo</h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Lista de Países y Territorios Autónomos
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Nombre (ES)</th>
                            <th>Nombre (EN)</th>
                            <th>Código Alfa-2</th>
                            <th>Código Alfa-3</th>
                            <th>Detalles</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for country in countries %}
                        <tr>
                            <td>{{country.name_spanish}}</td>
                            <td>{{country.name_english}}</td>
                            <td>{{country.code_alpha_two}}</td>
                            <td>{{country.code_alpha_three}}</td>
                            <td>
                                <a class="btn btn-info" href="{% url 'countries:cases-country' country.code_alpha_three %}">Ver</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/web/create_user.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>COVID Dashboard - Registro</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Registro</h3></div>
                                    {% for error in errors_1 %}
                                        {{ error }} <br>
                                    {% endfor %}
                                    {{errors_2}}
                                    <div class="card-body">
                                        <form method="POST">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputFirstNameAddress">Nombre</label>
                                                <input class="form-control py-4" id="inputFirstNameAddress" placeholder="Escribe tu nombre" name="first_name" />
                                            </div>
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputLastNameAddress">Apellido</label>
                                                <input class="form-control py-4" id="inputLastNameAddress" placeholder="Escribe tu apellido" name="last_name" />
                                            </div>
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputUsernameAddress">Usuario</label>
                                                <input class="form-control py-4" id="inputUsernameAddress" placeholder="Escribe tu usuario" name="username" />
                                            </div>
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputPassword">Contraseña</label>
                                                <input class="form-control py-4" id="inputPassword" type="password" placeholder="Escribe tu contraseña" name="password" />
                                            </div>
                                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <button class="btn btn-primary" type="submit">Continuar</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center">
                                        <div class="small"><a href="{% url 'login' %}">Iniciar Sesión</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Whale & Jaguar</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/web/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>COVID Dashboard - Login</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Iniciar Sesión</h3></div>
                                    {% if form.errors %}
                                        {% for field in form %}
                                            {% for error in field.errors%}
                                            <p>{{error|escape}}</p>
                                            {% endfor %}
                                        {% endfor %}
                                        {% for error in form.non_field_errors %}                        
                                            <p>{{ error|escape }}</p>                        
                                        {% endfor %}
                                    {% endif %}
                                    <div class="card-body">
                                        <form method="POST">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputUsernameAddress">Usuario</label>
                                                <input class="form-control py-4" id="inputUsernameAddress" placeholder="Escribe tu usuario" name="username" />
                                            </div>
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputPassword">Contraseña</label>
                                                <input class="form-control py-4" id="inputPassword" type="password" placeholder="Escribe tu contraseña" name="password" />
                                            </div>
                                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <button class="btn btn-primary" type="submit">Ingresar</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center">
                                        <div class="small"><a href="{% url 'users:create-user' %}">Registrarse</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Whale & Jaguar</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/web/master.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>COVID Dashboard</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <a class="navbar-brand" href="index.html">COVID Dashboard</a>
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" action="{% url 'countries:search-countries' %}">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Buscar país..." aria-label="Search" aria-describedby="basic-addon2" name="country_search" value="{{country_search}}" required/>
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="{% url 'logout' %}">Salir</a>
                    </div>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Casos</div>
                            <a class="nav-link" href="{% url 'cases:home' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-globe-americas"></i></div>
                                Global
                            </a>
                            <a class="nav-link" href="{% url 'countries:countries' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-flag"></i></div>
                                Por Países
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Sesión iniciada como:</div>
                        {{user.username}}
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    {% block content %}
                    {% endblock %}
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Whale & Jaguar</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'assets/demo/datatables-demo.js' %}"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>